apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: appstudio-utils-build-definitions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: appstudio-utils-build-definitions
    app.kubernetes.io/part-of: build-definitions
  name: appstudio-utils-build-definitions
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: appstudio-utils-build-definitions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: appstudio-utils-build-definitions
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
