apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: appstudio-utils-build-definitions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: appstudio-utils-build-definitions
    app.kubernetes.io/part-of: build-definitions
  name: appstudio-utils-build-definitions
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: appstudio-utils-build-definitions
status:
  loadBalancer: {}
